dist: trusty
sudo: false
language: go
go:
- 1.8.1

services: mysql
install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor

script:
- test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
- make test
- make vendor-status
- make vet
- export MYSQL_USERNAME=root
- export MYSQL_ENDPOINT=localhost:3306
- export MYSQL_PASSWORD=
- mysql -u root -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
- make testacc

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
